### ISSUE TITLE
[TEST] - Primeros errores

### ISSUE THREAD

**Issue by Galazord** [raullb34/practicasmanuellevi#6]
- Exportar en el index la app: module.exports = app;

- Al hacer un POST o cualquier consulta debe retornar siempre un JSON y no un String.

**Comment by Galazord** [comment]
Al añadir depósito te mando captura para que veas que indica que necesita un JSON para la respuesta. Y ten en cuenta que los POST devuelven un 201 y no un 200 ;)

![imagen](https://user-images.githubusercontent.com/9888356/162145929-8d0e6aa8-fc14-4d32-848a-4c59974c43fe.png)

**Comment by mlevitorresv** [comment]
hecho
